### PR TITLE
Update graphql-tools to ^0.4.2

### PR DESCRIPTION
**Pull request by diegonc**
Cherry-pick 761f38fef7b194f61acbd3e709ff64aef12c73e8 into server-only branch.

( for issue #9 )

### CODE REVIEW

**Comment by helfer** [comment]
@diegonc Can you add graphql@^0.5.0 as a dev dependency to package.json for this PR and the other one? That way the setup will still work the same, and people won't have to npm install graphql by hand.

**Comment by diegonc** [comment]
Sure, I'll do it tomorrow.

**Comment by diegonc** [comment]
Done!

**Comment by helfer** [comment]
Thanks!

**Pull request merged**
